### PR TITLE
Surveymonkey

### PR DESCRIPTION
**Pull request by tomltd**
A bunch of stuff has moved around to more logical places and changing the privacy/feedback sections to flexbox changed the portal so there are fixes for that too. Boom

### CODE REVIEW

**Comment by katjam** [comment]
:disappointed: On my chrome - with fairly lo-res monitor, I don't like the not having margin on the footer content.
no-page-margins

**Comment by katjam** [comment]
Also not sure there is enough visual clue that those are links nor that they are 2 different links - they run together.

no-page-margins1

**Comment by tomltd** [comment]
@katjam it's because you have to merge the css to master for travis to build it properly? Works a treat on local

screenshot from 2016-01-06 11 01 21

**Comment by katjam** [comment]
I am looking at the 2 github pages versions. Do you think thy are out of
date?

**Comment by tomltd** [comment]
Defo it hasn't compiled the css because it is not in the master branch. I think had this problem a lot before. I've just checked it out from here and I'm sure that's the case. You must have thought I was bonkers sending you the links next to each other like that :nut_and_bolt:

**Comment by katjam** [comment]
Never thought you were bonkers... not concentrating on my 'day off'. Sorry!

**Comment by katjam** [comment]
:shipit:

**Pull request merged**
