### PR TITLE
change style of done/disabled category buttons

### PR DESCRIPTION
**Pull request by tomltd**
I flicked the helioscissor scanner and came back with this. Tried a few different styles and this one is by far the best as it gives the impression the button has been pressed in.

screenshot from 2016-01-13 13 59 40

### CODE REVIEW

**Comment by katjam** [comment]
Looks good, but we may want to do a bit of user testing on this - Makes it
look a bit like a multi selected checkboxes ratehr than seen all the
questions.

Let's see what people think in practice.

**Comment by katjam** [comment]
:+1: :zap:

**Comment by tomltd** [comment]
@katjam After a chat with @harryharrold we have gone for the depressed buttons with done :after 

screenshot from 2016-01-13 14 32 21

**Comment by katjam** [comment]
I think that works better. :+1:

**Pull request merged**
