### PR TITLE
redesigned tick

### PR DESCRIPTION
**Pull request by tomltd**
created new tick, it's an svg so we can tweak the colors, add texture etc but just a first iteration to make sure I'm on the right track

### CODE REVIEW

**Comment by tomltd** [comment]
screenshot from 2015-11-04 11 59 59

**Comment by katjam** [comment]
I think it should be a single colour like the other graphics. so you can use transparent and light blue...

**Comment by tomltd** [comment]
@katjam how about this 
screenshot from 2015-11-04 13 56 21

**Comment by tomltd** [comment]
is this good to go now?

**Comment by katjam** [comment]
Yes, I think so.

**Pull request merged**
